src/base/FalconApp.C
tests/PT_H_diffusion/inp.i
tests/PT_H_gravity/inp.i
tests/PT_H_injection/inp.i
tests/PT_TH_elder/step1.i
tests/PT_TH_elder/step2_comp.i
tests/PT_TH_elder/step2_wseos.i
tests/PT_TH_faust/inp.i
tests/PT_TH_injection/inp.i
tests/PT_T_conduction/inp.i
tests/PT_T_convection/inp1.i
tests/PT_T_convection/inp2.i

Update to new syntax

---

src/materials/PTGeothermal.C

This branch gets Falcon compiling with the latest MOOSE.
Refs idaholab/moose#5917

Fix includes

---

tests/THM_injection/thm_transient.i

Fix test broken due to recent MOOSE change 

---

tests/PT_H_injection/inp.i
tests/PT_TH_injection/inp.i

...necessary for upcoming moose parser improvements.

input file syntax fixes

---

src/main.C

Migrate to shared pointers in main.C

---

tests/PT_T_convection/inp3.i

Specify bt linesearch for test that needs it

---

tests/THM_injection/thm_steady.i
tests/THM_injection/thm_transient.i

Remove deprecated incremental_form parameter from tests 

---

.gitmodules

Use https over ssh for moose submodule

---

NOTICE.txt

Adding the NOTICE.txt required by INL Tech Deployment

---

examples/multiapp_dfn_amr/matrix_app_amr.i

Fix subapp executions

---

test/tests/PT_T_convection/tests
test/tests/THM_injection/tests

Skip slow-running tests in dbg

---

examples/multiapp_dfn_amr/frac_app_lineSource.i
test/tests/time_integrated_reporter/main.i

Fixed unused parameters

---

examples/multiapp_dfn_amr/matrix_app_amr.i
examples/multiapp_dfn_amr/matrix_app_amr_orig.i
examples/multiapp_dfn_amr/matrix_app_lineSource_amr.i

refs idaholab/moose#24237
SelfAux here was abusive. It's doing a variable family conversion

Use ProjectionAux instead of SelfAux since performing a projection

---

.gitignore
doc/content/getting_started/falcon_conda.md
doc/content/getting_started/falcon_windows10.md
doc/content/getting_started/install_falcon.md
doc/content/getting_started/installation/index.md
doc/content/getting_started/installation/tutorial/index.md

Update the getting started pages.
Add resource file to gitignore while here.
Closes #130

Update getting started pages

---

src/base/FalconApp.C

Updating module registration

---

include/postprocessors/PTMassSideFluxAverage.h
include/postprocessors/TimeIntegratedReporterValue.h
src/postprocessors/PTMassSideFluxAverage.C
src/postprocessors/TimeIntegratedReporterValue.C

Switched to const getValue

---

src/base/FalconApp.C
src/main.C
test/src/base/FalconTestApp.C
unit/src/main.C

Adapt to the new changes in MOOSE(https://github.com/idaholab/moose/pull/25994)

Clean up main.C and explicitly register dependent app

---

Makefile
doc/config.yml

refs idaholab/moose#25584
fixes next fails

Rename heat conduciton module 

---

examples/multiapp_dfn_amr/frac_app_lineSource.i
examples/multiapp_dfn_amr/fracture_only_aperture_changing_amr.i
examples/multiapp_dfn_amr/tests

in tabulatedFP
refs idaholab/moose#28021

Add boolean to prepare for ban of specifying both fp and tabulation

---

src/base/FalconApp.C

This is required for https://github.com/idaholab/moose/pull/29593.

Remove closures enumeration capability

---

test/tests/THM_injection/tests

Loosen injection tol
